<?php

function dj_gmap_init(){
	if (current_path() == "node/34") {

		drupal_add_js('https://maps.googleapis.com/maps/api/js', 'external');
		drupal_add_js(drupal_get_path('module', 'dj_gmap') . '/dj_gmap.js');   


/*
		drupal_add_js('function initialize() {
        var mapCanvas = document.getElementById("map-canvas");
        var mapOptions = {
          center: new google.maps.LatLng(40.8183166, -74.3908328),
          zoom: 14,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        }
        var map = new google.maps.Map(mapCanvas, mapOptions)
      }
      google.maps.event.addDomListener(window, "load", initialize);', 'inline');
*/

	};
}




/*
    <style>
      #map-canvas {
        width: 500px;
        height: 400px;
      }
    </style>
    <script>
      function initialize() {
        var mapCanvas = document.getElementById('map-canvas');
        var mapOptions = {
          center: new google.maps.LatLng(44.5403, -78.5463),
          zoom: 8,
          mapTypeId: google.maps.MapTypeId.ROADMAP
        }
        var map = new google.maps.Map(mapCanvas, mapOptions)
      }
      google.maps.event.addDomListener(window, 'load', initialize);
    </script>
*/